name: test-macos

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: macos-latest
    name: AVA & Codecov
    strategy:
      fail-fast: false
      matrix:
        node: [14, 12, 10]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install lib dependencies
        run: |
          npm install --production
          npm list --prod --depth=0
      - name: Install dev dependencies
        run: |
          npm install
          npm list --dev --depth=0
      - name: Run tests
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
